### ISSUE TITLE
Empty PyPI listing

### ISSUE THREAD

**Issue by pnewstein** [schlegelp/xform#4]
The PyPI listing for this project appears to be empty. 

```bash
pip install xform
python -c "import xform"
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'xform'
```

Installing from github works fine.

**Comment by schlegelp** [comment]
Yeah, I ran out of steam on this project. I think I reserved `xform` on PyPI but never actually uploaded a working version. Happy to publish to PyPI if you find it useful.

**Comment by schlegelp** [comment]
Pushed to PyPI!
